version: '3.3'
services:
   db:
     image: mysql:5.7
     container_name: nodejs-sql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: test@123
       MYSQL_DATABASE: userlog
       MYSQL_USER: test
       MYSQL_PASSWORD: test@123
     ports:
      - "127.0.0.1:3307:3306"

volumes:
  db_data:

